/**
 * Copy resources/android/ into the generated native project.
 *
 * Wired to the `capacitor:sync:after` npm-script hook, so every `cap sync` — and therefore
 * every `npm run dev:android`, `cap:android` and CI build — restores it without anyone
 * remembering to. Also runnable on its own as `npm run android:res`.
 *
 * It exists because `android/` is gitignored: it is regenerated by `npx cap add android` on
 * every clone, which brings back Capacitor's own placeholder logo. The launcher icons are a
 * build input, not a build output, so they live in a committed tree and get copied in.
 *
 * No image work here and no dependencies — scripts/android-icons.ts is what produces the
 * tree, and it only has to run when the logo changes.
 */
import { access, cp } from 'node:fs/promises';

const FROM = 'resources/android';
const TO = 'android/app/src/main/res';

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

// Both sides are optional on purpose. This runs from a Capacitor lifecycle hook, which also
// fires for iOS-only syncs and before `cap add android` has ever run — a hook that failed
// there would break `cap sync` itself, for a launcher icon.
if (!(await exists(FROM))) {
  console.log(`android:res — no ${FROM}/, nothing to copy (run \`npm run android:icons\`).`);
  process.exit(0);
}
if (!(await exists(TO))) {
  console.log(`android:res — no ${TO}/, skipping (add the platform with \`npx cap add android\`).`);
  process.exit(0);
}

// Merge, don't replace: the template's own res/ holds values/, layout/ and xml/ that we do
// not generate, and dropping those takes the app's theme and FileProvider with them.
await cp(FROM, TO, { recursive: true, force: true });
console.log(`android:res — ${FROM}/ -> ${TO}/`);
