/**
 * Copy resources/android/ into the generated native project — tinted on a local build.
 *
 * Run by `npm run android:init` right after the platform is generated, and again ahead of
 * every `android:dev` and `android:build`; also runnable on its own as `npm run android:res`.
 *
 * It exists because `android/` is gitignored: it is regenerated by `npm run android:init` on
 * every clone, which brings back Tauri's own placeholder logo. The launcher icons are a
 * build input, not a build output, so they live in a committed tree and get copied in.
 *
 * Running before every build, not only after init, is what makes the icon follow the BUILD
 * rather than whichever run last touched `gen/`. A generated project outlives the build that
 * made it, so a copy made once at init would leave a local build wearing the brand icon it
 * was initialised with, or a `COSMOS_ICONS=release` build wearing the dev tint.
 *
 * A dev build sends every PNG through the dev tint on the way in (scripts/devIcons.ts); a
 * release build copies the tree byte for byte. resources/android/ is never written to either
 * way — scripts/android-icons.ts is what produces it, and only when the logo changes.
 */
import { access, cp, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { iconFlavor, tintPng } from './devIcons.ts';

const FROM = 'resources/android';
const TO = 'src-tauri/gen/android/app/src/main/res';

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

// Both sides are optional on purpose. This runs right after `tauri android init`, which may
// runs on a checkout where the Android platform has never been generated — a step that
// failed there would break `npm run android:init` itself, for a launcher icon.
if (!(await exists(FROM))) {
  console.log(`android:res — no ${FROM}/, nothing to copy (run \`npm run android:icons\`).`);
  process.exit(0);
}
if (!(await exists(TO))) {
  console.log(`android:res — no ${TO}/, skipping (generate it with \`npm run android:init\`).`);
  process.exit(0);
}

const flavor = iconFlavor();

// Merge, don't replace: the template's own res/ holds values/, layout/ and xml/ that we do
// not generate, and dropping those takes the app's theme and FileProvider with them.
if (flavor === 'release') {
  await cp(FROM, TO, { recursive: true, force: true });
} else {
  for (const entry of await readdir(FROM, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const from = join(entry.parentPath, entry.name);
    const to = join(TO, relative(FROM, from));
    const bytes = await readFile(from);
    await mkdir(dirname(to), { recursive: true });
    // The adaptive-icon XML only points at the mipmaps, so it goes in untouched.
    await writeFile(to, entry.name.endsWith('.png') ? await tintPng(bytes) : bytes);
  }
}
console.log(`android:res — ${FROM}/ -> ${TO}/ [${flavor} icons]`);
