/**
 * Stamp package.json's version into the generated native projects.
 *
 * Wired to the `capacitor:sync:after` npm-script hook next to scripts/android-res.ts and
 * scripts/native-permissions.ts, so every `cap sync` — and therefore every `npm run
 * dev:android`, `cap:android` and CI build — restores it. Also runnable on its own as
 * `npm run native:version`.
 *
 * It exists for the same reason those two do: `android/` and `ios/` are gitignored and
 * regenerated by `npx cap add`, which brings back Capacitor's template values — `versionCode 1`
 * / `versionName "1.0"` on Android, `MARKETING_VERSION = 1.0` / `CURRENT_PROJECT_VERSION = 1`
 * on iOS. A version edited straight into android/ is gone on the next clone.
 *
 * That default is not cosmetic. Play Console rejects an upload whose `versionCode` it has
 * already seen, so every release built from a fresh checkout would collide on 1; App Store
 * Connect does the same with `CFBundleVersion`. And an installed build reporting 1.0 while the
 * app's own About screen reports 1.2.4 makes a bug report unattributable to a release.
 *
 * package.json is the single source of truth here exactly as it is for `APP_VERSION`
 * (src/constants/app.ts) and the extension manifest — one number, derived everywhere, never
 * copied. There is no test pinning this against a literal, for the reason
 * tests/unit/version.test.ts spells out: two copies of a version cannot be kept honest by
 * asserting they agree.
 *
 * No XML parser, no dependencies, and no image work — both files are line-oriented and the
 * replacements are idempotent, so running this twice changes nothing.
 */
import { access, readFile, writeFile } from 'node:fs/promises';

const PKG = 'package.json';
const ANDROID_GRADLE = 'android/app/build.gradle';
const IOS_PBXPROJ = 'ios/App/App.xcodeproj/project.pbxproj';

const log = (msg: string) => console.log(`native:version — ${msg}`);

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * `1.2.4-dev.31` -> `{ core: '1.2.4', name: '1.2.4-dev.31' }`.
 *
 * The two halves go to different places. Android's `versionName` is a free string, so it keeps
 * the prerelease suffix and a tester can tell two dev builds apart. Apple's
 * `CFBundleShortVersionString` is validated as at most three dot-separated integers, so iOS gets
 * the core only — a marketing version of `1.2.4-dev.31` fails the App Store upload, not the
 * build, which is the worst place to find out.
 */
function parseVersion(raw: string): { core: string; name: string; parts: number[] } {
  const core = raw.split('-')[0];
  const parts = core.split('.').map((n) => Number.parseInt(n, 10));
  if (parts.length !== 3 || parts.some((n) => !Number.isInteger(n) || n < 0)) {
    throw new Error(`native:version — ${PKG} version "${raw}" is not semver X.Y.Z`);
  }
  return { core, name: raw, parts };
}

/**
 * A single monotonically-increasing integer, because that is the only shape Android and iOS
 * accept for the build number they compare across releases.
 *
 * `major * 10_000 + minor * 100 + patch` keeps the semver ordering as long as minor and patch
 * stay under 100 — checked below rather than assumed, since the failure is a release that
 * silently sorts BELOW the one before it and Play Console refuses as a downgrade.
 *
 * The prerelease suffix is deliberately not encoded: a `-dev.N` build shares its core's code,
 * and Android allows reinstalling over an equal code with the same signature, which is exactly
 * what a tester does. `NATIVE_VERSION_CODE` overrides the whole thing for the case this scheme
 * cannot express — a hotfix that has to outrank an already-uploaded build without a bump.
 */
function versionCode(parts: number[]): number {
  const override = process.env.NATIVE_VERSION_CODE;
  if (override) {
    const n = Number.parseInt(override, 10);
    if (!Number.isInteger(n) || n <= 0) {
      throw new Error(`native:version — NATIVE_VERSION_CODE="${override}" is not a positive integer`);
    }
    return n;
  }
  const [major, minor, patch] = parts;
  if (minor > 99 || patch > 99) {
    throw new Error(
      `native:version — ${major}.${minor}.${patch} overflows the versionCode scheme (minor/patch must stay < 100). ` +
        'Set NATIVE_VERSION_CODE, or widen the scheme here — never let it wrap.',
    );
  }
  return major * 10_000 + minor * 100 + patch;
}

/* ------------------------------- android ------------------------------- */

/**
 * Optional on purpose, exactly as in android-res.ts: this runs from a Capacitor lifecycle hook,
 * which also fires for iOS-only syncs and before `cap add android` has ever run. A hook that
 * failed there would break `cap sync` itself, over a version string.
 */
async function stampAndroid(name: string, code: number): Promise<void> {
  if (!(await exists(ANDROID_GRADLE))) {
    log(`no ${ANDROID_GRADLE}, skipping (add the platform with \`npx cap add android\`).`);
    return;
  }
  const before = await readFile(ANDROID_GRADLE, 'utf8');
  if (!/versionCode\s+\d+/.test(before) || !/versionName\s+"[^"]*"/.test(before)) {
    log(`${ANDROID_GRADLE} declares no versionCode/versionName — leaving it alone.`);
    return;
  }
  // Anchored on the property names rather than on the template's exact line, so a reformat by
  // Android Studio or a `cap migrate` does not silently stop matching.
  const after = before
    .replace(/versionCode\s+\d+/, `versionCode ${code}`)
    .replace(/versionName\s+"[^"]*"/, `versionName "${name}"`);
  if (after === before) {
    log(`${ANDROID_GRADLE} already at ${name} (${code}).`);
    return;
  }
  await writeFile(ANDROID_GRADLE, after);
  log(`${ANDROID_GRADLE} -> versionName "${name}", versionCode ${code}.`);
}

/* --------------------------------- ios --------------------------------- */

/**
 * Capacitor's iOS template writes `$(MARKETING_VERSION)` / `$(CURRENT_PROJECT_VERSION)` into
 * Info.plist and defines both in the pbxproj — once per build configuration, hence `replaceAll`.
 * Patching Info.plist instead would put a literal where a build setting is expected, and the two
 * would disagree the moment Xcode touched the project.
 */
async function stampIos(core: string, code: number): Promise<void> {
  if (!(await exists(IOS_PBXPROJ))) {
    log(`no ${IOS_PBXPROJ}, skipping (add the platform with \`npx cap add ios\`, on macOS).`);
    return;
  }
  const before = await readFile(IOS_PBXPROJ, 'utf8');
  if (!before.includes('MARKETING_VERSION')) {
    log(`${IOS_PBXPROJ} defines no MARKETING_VERSION — leaving it alone.`);
    log('  (older templates put CFBundleShortVersionString straight in Info.plist; set it by hand.)');
    return;
  }
  const after = before
    .replaceAll(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${core};`)
    .replaceAll(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${code};`);
  if (after === before) {
    log(`${IOS_PBXPROJ} already at ${core} (${code}).`);
    return;
  }
  await writeFile(IOS_PBXPROJ, after);
  log(`${IOS_PBXPROJ} -> MARKETING_VERSION ${core}, CURRENT_PROJECT_VERSION ${code}.`);
}

const { version } = JSON.parse(await readFile(PKG, 'utf8')) as { version: string };
const { core, name, parts } = parseVersion(version);
const code = versionCode(parts);

await stampAndroid(name, code);
await stampIos(core, code);
