/**
 * Declare, in the generated native projects, the permissions the WebView needs at runtime.
 *
 * Wired to the `capacitor:sync:after` npm-script hook next to scripts/android-res.ts, so every
 * `cap sync` — and therefore every `npm run dev:android`, `cap:android` and CI build — restores
 * it. Also runnable on its own as `npm run native:perms`.
 *
 * It exists for the same reason android-res.ts does: `android/` and `ios/` are gitignored and
 * regenerated by `npx cap add`, which brings back Capacitor's template manifest — INTERNET and
 * nothing else. A permission edited straight into android/ is gone on the next clone, and the
 * failure is silent: the camera simply never opens.
 *
 * Nothing here grants anything. It declares what the OS is *allowed to ask the user for*; the
 * prompt itself is Capacitor's, raised the first time the web layer touches the API.
 *
 * No image work, no XML parser and no dependencies — the two files are line-oriented templates
 * and the insertions are checked for before they are made, so running this twice is a no-op.
 */
import { access, readFile, writeFile } from 'node:fs/promises';

const ANDROID_MANIFEST = 'android/app/src/main/AndroidManifest.xml';
const IOS_PLIST = 'ios/App/App/Info.plist';

/**
 * `<uses-permission>` entries.
 *
 * CAMERA is not optional for the scanner: `src/features/extras/ScanQR.tsx` calls
 * `navigator.mediaDevices.getUserMedia`, Capacitor's BridgeWebChromeClient turns that into a
 * runtime request for `Manifest.permission.CAMERA`, and Android denies a request for a
 * permission the manifest never declared *without showing a dialog*. The user sees "camera
 * unavailable" and has nothing to tap.
 */
const PERMISSIONS = ['android.permission.CAMERA'];

/**
 * `<uses-feature ... required="false">` entries.
 *
 * Google Play reads a CAMERA permission as an implicit *requirement* for
 * `android.hardware.camera` and `android.hardware.camera.autofocus`, and hides the listing from
 * every device that has neither — emulators, Chromebooks, camera-less tablets. The scanner is
 * one screen out of thirty and it already ships two fallbacks (upload an image, paste one), so
 * the app must stay installable without a camera. `required="false"` is what says so.
 */
const FEATURES = ['android.hardware.camera', 'android.hardware.camera.autofocus'];

/**
 * `<queries>` — package visibility, API 30+.
 *
 * The KYC photo step (`src/features/fiat/PhotoStep.tsx`) renders `<input type="file" capture>`,
 * which Capacitor serves from `onShowFileChooser` by resolving an ACTION_IMAGE_CAPTURE intent
 * first. Under targetSdk 30+ an app cannot see another package's activities unless it declares
 * the intent it wants to match, so `resolveActivity` returns null on every device, Capacitor
 * logs a warning nobody reads and falls back to the gallery picker: "take a photo" quietly
 * becomes "pick a file".
 */
const INTENT_QUERIES = ['android.media.action.IMAGE_CAPTURE'];

/**
 * iOS purpose strings.
 *
 * Stricter than Android's: a missing key is not a denial but a crash — the OS terminates the
 * app the moment the API is touched. These are the App Store's base-language (English) strings;
 * translating them means adding `InfoPlist.strings` per locale, not editing these.
 */
const IOS_USAGE: { key: string; value: string }[] = [
  {
    key: 'NSCameraUsageDescription',
    value: 'Cosmos Wallet uses the camera to scan Stellar payment QR codes and to photograph the documents an identity check asks for.',
  },
  {
    key: 'NSPhotoLibraryUsageDescription',
    value: 'Cosmos Wallet opens your photo library when you import a QR image, choose a wallet avatar, or attach a document to an identity check.',
  },
];

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

const log = (msg: string) => console.log(`native:perms — ${msg}`);

/* ------------------------------- android ------------------------------- */

/**
 * Both sides are optional on purpose, exactly as in android-res.ts: this runs from a Capacitor
 * lifecycle hook, which also fires for iOS-only syncs and before `cap add android` has ever
 * run. A hook that failed there would break `cap sync` itself, over a permission.
 */
async function patchAndroid(): Promise<void> {
  if (!(await exists(ANDROID_MANIFEST))) {
    log(`no ${ANDROID_MANIFEST}, skipping (add the platform with \`npx cap add android\`).`);
    return;
  }

  const before = await readFile(ANDROID_MANIFEST, 'utf8');
  const lines: string[] = [];

  // Match on the fully-qualified name, not on the whole element: Capacitor's template writes
  // ` />` where an Android Studio edit writes `/>`, and a byte comparison would duplicate the
  // entry — which aapt rejects as a duplicate attribute, failing the build.
  for (const name of PERMISSIONS) {
    if (!before.includes(`"${name}"`)) lines.push(`    <uses-permission android:name="${name}" />`);
  }
  for (const name of FEATURES) {
    if (!before.includes(`"${name}"`)) {
      lines.push(`    <uses-feature android:name="${name}" android:required="false" />`);
    }
  }

  const queries = INTENT_QUERIES.filter((action) => !before.includes(`"${action}"`));
  if (queries.length) {
    lines.push('    <queries>');
    for (const action of queries) {
      lines.push('        <intent>', `            <action android:name="${action}" />`, '        </intent>');
    }
    lines.push('    </queries>');
  }

  if (!lines.length) {
    log(`${ANDROID_MANIFEST} already declares everything.`);
    return;
  }

  // Before </manifest> rather than after the template's `<!-- Permissions -->` comment: the
  // comment is the template's, so it is one `cap migrate` away from moving or disappearing,
  // while the closing tag is the one landmark an AndroidManifest cannot be missing.
  const close = before.lastIndexOf('</manifest>');
  if (close < 0) {
    log(`${ANDROID_MANIFEST} has no </manifest> — leaving it alone.`);
    return;
  }
  const block = `\n    <!-- Added by scripts/native-permissions.ts — android/ is generated. -->\n${lines.join('\n')}\n\n`;
  await writeFile(ANDROID_MANIFEST, before.slice(0, close) + block + before.slice(close));
  log(`${ANDROID_MANIFEST} +${lines.length} line(s).`);
}

/* --------------------------------- ios --------------------------------- */

async function patchIos(): Promise<void> {
  if (!(await exists(IOS_PLIST))) {
    log(`no ${IOS_PLIST}, skipping (add the platform with \`npx cap add ios\`, on macOS).`);
    return;
  }

  const before = await readFile(IOS_PLIST, 'utf8');
  const missing = IOS_USAGE.filter((entry) => !before.includes(`<key>${entry.key}</key>`));
  if (!missing.length) {
    log(`${IOS_PLIST} already declares everything.`);
    return;
  }

  // The root <dict> is the last one to close, so its terminator is the last one in the file.
  const close = before.lastIndexOf('</dict>');
  if (close < 0) {
    log(`${IOS_PLIST} has no </dict> — leaving it alone.`);
    return;
  }
  // Tabs, because that is what Capacitor's template uses and a plist diff should stay readable.
  const block = missing.map((e) => `\t<key>${e.key}</key>\n\t<string>${e.value}</string>\n`).join('');
  await writeFile(IOS_PLIST, before.slice(0, close) + block + before.slice(close));
  log(`${IOS_PLIST} +${missing.length} key(s).`);
}

await patchAndroid();
await patchIos();
