/**
 * Declare, in the generated native projects, the permissions the WebView needs at runtime.
 *
 * Wired to the `capacitor:sync:after` npm-script hook next to scripts/android-res.ts, so every
 * `cap sync` — and therefore every `npm run dev:android`, `cap:android` and CI build — restores
 * it. Also runnable on its own as `npm run native:perms`.
 *
 * It exists for the same reason android-res.ts does: `android/` and `ios/` are gitignored and
 * regenerated by `npx cap add`, which brings back Capacitor's template manifest — INTERNET and
 * nothing else. A permission edited straight into android/ is gone on the next clone, and the
 * failure is silent: the camera simply never opens.
 *
 * Nothing here grants anything. It declares what the OS is *allowed to ask the user for*; the
 * prompt itself is Capacitor's, raised the first time the web layer touches the API.
 *
 * No image work, no XML parser and no dependencies — the two files are line-oriented templates
 * and the insertions are checked for before they are made, so running this twice is a no-op.
 */
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';

const ANDROID_MANIFEST = 'android/app/src/main/AndroidManifest.xml';
const ANDROID_XML_DIR = 'android/app/src/main/res/xml';
const IOS_PLIST = 'ios/App/App/Info.plist';
const IOS_PRIVACY_MANIFEST = 'ios/App/App/PrivacyInfo.xcprivacy';
const IOS_PBXPROJ = 'ios/App/App.xcodeproj/project.pbxproj';

/**
 * `<uses-permission>` entries.
 *
 * CAMERA is not optional for the scanner: `src/features/extras/ScanQR.tsx` calls
 * `navigator.mediaDevices.getUserMedia`, Capacitor's BridgeWebChromeClient turns that into a
 * runtime request for `Manifest.permission.CAMERA`, and Android denies a request for a
 * permission the manifest never declared *without showing a dialog*. The user sees "camera
 * unavailable" and has nothing to tap.
 *
 * USE_BIOMETRIC is the same story for `src/lib/deviceAuth.ts`: BiometricPrompt refuses to show
 * without it, so "unlock with your fingerprint" fails on a device that has one enrolled, and the
 * only clue is a logcat line. It is a normal-protection permission — declaring it raises no
 * install-time prompt and asks the user for nothing. There is deliberately no USE_FINGERPRINT
 * here: it was deprecated in API 28, USE_BIOMETRIC covers every version this app targets, and
 * declaring it would re-introduce the Play filtering that `required="false"` exists to undo.
 */
const PERMISSIONS = ['android.permission.CAMERA', 'android.permission.USE_BIOMETRIC'];

/**
 * `<uses-feature ... required="false">` entries.
 *
 * Google Play reads a CAMERA permission as an implicit *requirement* for
 * `android.hardware.camera` and `android.hardware.camera.autofocus`, and hides the listing from
 * every device that has neither — emulators, Chromebooks, camera-less tablets. The scanner is
 * one screen out of thirty and it already ships two fallbacks (upload an image, paste one), so
 * the app must stay installable without a camera. `required="false"` is what says so.
 *
 * `android.hardware.fingerprint` is listed for the same defensive reason, and it matters more
 * here than it looks: the wallet must stay installable on a phone with no sensor at all, because
 * that phone can still use the device-credential tier in `lib/deviceAuth.ts` — and it must stay
 * installable on one with a sensor nobody enrolled, because the password is always there.
 * Neither device may be filtered out of the listing over a convenience feature.
 */
const FEATURES = [
  'android.hardware.camera',
  'android.hardware.camera.autofocus',
  'android.hardware.fingerprint',
];

/**
 * `<queries>` — package visibility, API 30+.
 *
 * The KYC photo step (`src/features/fiat/PhotoStep.tsx`) renders `<input type="file" capture>`,
 * which Capacitor serves from `onShowFileChooser` by resolving an ACTION_IMAGE_CAPTURE intent
 * first. Under targetSdk 30+ an app cannot see another package's activities unless it declares
 * the intent it wants to match, so `resolveActivity` returns null on every device, Capacitor
 * logs a warning nobody reads and falls back to the gallery picker: "take a photo" quietly
 * becomes "pick a file".
 */
const INTENT_QUERIES = ['android.media.action.IMAGE_CAPTURE'];

/**
 * iOS purpose strings.
 *
 * Stricter than Android's: a missing key is not a denial but a crash — the OS terminates the
 * app the moment the API is touched. These are the App Store's base-language (English) strings;
 * translating them means adding `InfoPlist.strings` per locale, not editing these.
 */
const IOS_USAGE: { key: string; value: string }[] = [
  {
    key: 'NSCameraUsageDescription',
    value: 'Cosmos Wallet uses the camera to scan Stellar payment QR codes and to photograph the documents an identity check asks for.',
  },
  {
    // Face ID only. Touch ID and the device passcode need no purpose string, but a
    // missing NSFaceIDUsageDescription is not a denied prompt — iOS terminates the app
    // the moment LocalAuthentication is touched, so the first Face ID unlock on a Face ID
    // phone would be a crash rather than a refusal.
    key: 'NSFaceIDUsageDescription',
    value: 'Cosmos Wallet uses Face ID to unlock your wallet and confirm signatures, so you do not have to type your password every time. Your password always keeps working.',
  },
  {
    key: 'NSPhotoLibraryUsageDescription',
    value: 'Cosmos Wallet opens your photo library when you import a QR image, choose a wallet avatar, or attach a document to an identity check.',
  },
];

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

const log = (msg: string) => console.log(`native:perms — ${msg}`);

/* ------------------------------- android ------------------------------- */

/**
 * Both sides are optional on purpose, exactly as in android-res.ts: this runs from a Capacitor
 * lifecycle hook, which also fires for iOS-only syncs and before `cap add android` has ever
 * run. A hook that failed there would break `cap sync` itself, over a permission.
 */
async function patchAndroid(): Promise<void> {
  if (!(await exists(ANDROID_MANIFEST))) {
    log(`no ${ANDROID_MANIFEST}, skipping (add the platform with \`npx cap add android\`).`);
    return;
  }

  const before = await readFile(ANDROID_MANIFEST, 'utf8');
  const lines: string[] = [];

  // Match on the fully-qualified name, not on the whole element: Capacitor's template writes
  // ` />` where an Android Studio edit writes `/>`, and a byte comparison would duplicate the
  // entry — which aapt rejects as a duplicate attribute, failing the build.
  for (const name of PERMISSIONS) {
    if (!before.includes(`"${name}"`)) lines.push(`    <uses-permission android:name="${name}" />`);
  }
  for (const name of FEATURES) {
    if (!before.includes(`"${name}"`)) {
      lines.push(`    <uses-feature android:name="${name}" android:required="false" />`);
    }
  }

  const queries = INTENT_QUERIES.filter((action) => !before.includes(`"${action}"`));
  if (queries.length) {
    lines.push('    <queries>');
    for (const action of queries) {
      lines.push('        <intent>', `            <action android:name="${action}" />`, '        </intent>');
    }
    lines.push('    </queries>');
  }

  if (!lines.length) {
    log(`${ANDROID_MANIFEST} already declares everything.`);
    return;
  }

  // Before </manifest> rather than after the template's `<!-- Permissions -->` comment: the
  // comment is the template's, so it is one `cap migrate` away from moving or disappearing,
  // while the closing tag is the one landmark an AndroidManifest cannot be missing.
  const close = before.lastIndexOf('</manifest>');
  if (close < 0) {
    log(`${ANDROID_MANIFEST} has no </manifest> — leaving it alone.`);
    return;
  }
  const block = `\n    <!-- Added by scripts/native-permissions.ts — android/ is generated. -->\n${lines.join('\n')}\n\n`;
  await writeFile(ANDROID_MANIFEST, before.slice(0, close) + block + before.slice(close));
  log(`${ANDROID_MANIFEST} +${lines.length} line(s).`);
}

/* --------------------------------- ios --------------------------------- */

async function patchIos(): Promise<void> {
  if (!(await exists(IOS_PLIST))) {
    log(`no ${IOS_PLIST}, skipping (add the platform with \`npx cap add ios\`, on macOS).`);
    return;
  }

  const before = await readFile(IOS_PLIST, 'utf8');
  const missing = IOS_USAGE.filter((entry) => !before.includes(`<key>${entry.key}</key>`));
  if (!missing.length) {
    log(`${IOS_PLIST} already declares everything.`);
    return;
  }

  // The root <dict> is the last one to close, so its terminator is the last one in the file.
  const close = before.lastIndexOf('</dict>');
  if (close < 0) {
    log(`${IOS_PLIST} has no </dict> — leaving it alone.`);
    return;
  }
  // Tabs, because that is what Capacitor's template uses and a plist diff should stay readable.
  const block = missing.map((e) => `\t<key>${e.key}</key>\n\t<string>${e.value}</string>\n`).join('');
  await writeFile(IOS_PLIST, before.slice(0, close) + block + before.slice(close));
  log(`${IOS_PLIST} +${missing.length} key(s).`);
}

/* ---------------------------- android backup ---------------------------- */

/**
 * Keep the encrypted vault off Google Drive.
 *
 * Capacitor's template writes `android:allowBackup="true"`, and Android Auto Backup then
 * uploads the app's SharedPreferences to the user's Drive. That is where `lib/storage.ts`
 * puts everything: the AES-GCM sealed seed (`cosmos.w.<id>`), the sealed device-unlock
 * envelope (`cosmos.auth.<id>`), and the PLAINTEXT wallet list — which carries name, email,
 * birthdate, gender and the avatar image. The sealed blobs are only as strong as an 8-char
 * minimum password once they are somewhere an attacker can grind them offline, and the
 * plaintext half needs no attack at all. A non-custodial wallet's storage should not leave
 * the device it was created on.
 *
 * Two mechanisms, because one is not enough on a modern target. `allowBackup="false"` stops
 * cloud backup. Device-to-device transfer on Android 12+ is governed separately by
 * `dataExtractionRules`, so a manifest with only the flag still hands the vault to the next
 * phone during setup-wizard migration. `fullBackupContent` covers API 30 and below, where
 * `dataExtractionRules` is ignored.
 */
const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/native-permissions.ts — android/ is a build output. -->
<data-extraction-rules>
    <cloud-backup>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </cloud-backup>
    <device-transfer>
        <exclude domain="root" />
        <exclude domain="file" />
        <exclude domain="database" />
        <exclude domain="sharedpref" />
        <exclude domain="external" />
    </device-transfer>
</data-extraction-rules>
`;

const BACKUP_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/native-permissions.ts — API 30 and below. -->
<full-backup-content>
    <exclude domain="root" path="." />
    <exclude domain="file" path="." />
    <exclude domain="database" path="." />
    <exclude domain="sharedpref" path="." />
    <exclude domain="external" path="." />
</full-backup-content>
`;

async function patchAndroidBackup(): Promise<void> {
  if (!(await exists(ANDROID_MANIFEST))) return; // patchAndroid() already said so

  await mkdir(ANDROID_XML_DIR, { recursive: true });
  await writeFile(`${ANDROID_XML_DIR}/data_extraction_rules.xml`, DATA_EXTRACTION_RULES);
  await writeFile(`${ANDROID_XML_DIR}/backup_rules.xml`, BACKUP_RULES);

  const before = await readFile(ANDROID_MANIFEST, 'utf8');
  let after = before;

  // The template always writes the attribute, so this is a replace rather than an insert.
  // Rewriting `="true"` specifically (not the whole line) keeps the edit idempotent and
  // leaves an already-false manifest untouched.
  after = after.replace(/android:allowBackup="true"/g, 'android:allowBackup="false"');

  // FAIL LOUD, NOT OPEN. Everything below anchors on `android:allowBackup="false"` being
  // present. If a future Capacitor template stops writing the attribute at all, the replace
  // above matches nothing, both insertions find no anchor, `after === before`, and the old
  // code logged "already keeps app data out of backups." for a build shipping the platform
  // default — which is `true`. The whole point of this function is that the sealed seed does
  // not go to Google Drive; a silent no-op is the one outcome it must never have.
  if (!after.includes('android:allowBackup="false"')) {
    log(`ERROR — ${ANDROID_MANIFEST} declares no android:allowBackup attribute.`);
    log('  The Capacitor template changed shape. Android Auto Backup defaults to ON, which');
    log('  uploads the sealed vault and the plaintext wallet list to the user\'s Drive.');
    log('  Add android:allowBackup="false" to <application> before shipping this build.');
    process.exitCode = 1;
    return;
  }

  for (const [attr, value] of [
    ['android:dataExtractionRules', '@xml/data_extraction_rules'],
    ['android:fullBackupContent', '@xml/backup_rules'],
  ] as const) {
    if (after.includes(`${attr}=`)) continue;
    // Anchor on the allowBackup attribute we just normalised: it is on the <application>
    // element, which is the only place these belong, and it is guaranteed present.
    after = after.replace('android:allowBackup="false"', `android:allowBackup="false"\n        ${attr}="${value}"`);
  }

  if (after === before) {
    log(`${ANDROID_MANIFEST} already keeps app data out of backups.`);
    return;
  }
  await writeFile(ANDROID_MANIFEST, after);
  log(`${ANDROID_MANIFEST} — backups disabled (cloud + device transfer).`);
}

/* --------------------------- ios privacy manifest --------------------------- */

/**
 * `PrivacyInfo.xcprivacy` — required by App Store review since May 2024.
 *
 * `@capacitor/preferences` stores through `UserDefaults`, which Apple classifies as a
 * required-reason API. An app that touches one without declaring it is rejected
 * automatically (`ITMS-91053: Missing API declaration`), before a human ever looks at it.
 * `CA92.1` is the reason code for "access info from the app itself" — which is exactly what
 * this is: the wallet reads back its own sealed blobs, never another app's data.
 *
 * `NSPrivacyTracking` is false and the collected-data list is empty because the WALLET
 * collects nothing on its own behalf. The fiat on/off-ramp does transmit identity data to a
 * third party, but that flows to CosmosPay's own service under its own disclosure; if that
 * ever becomes first-party collection, `NSPrivacyCollectedDataTypes` has to say so here too.
 */
const IOS_PRIVACY_MANIFEST_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/native-permissions.ts — ios/ is a build output. -->
<plist version="1.0">
<dict>
\t<key>NSPrivacyTracking</key>
\t<false/>
\t<key>NSPrivacyTrackingDomains</key>
\t<array/>
\t<key>NSPrivacyCollectedDataTypes</key>
\t<array/>
\t<key>NSPrivacyAccessedAPITypes</key>
\t<array>
\t\t<dict>
\t\t\t<key>NSPrivacyAccessedAPIType</key>
\t\t\t<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
\t\t\t<key>NSPrivacyAccessedAPITypeReasons</key>
\t\t\t<array>
\t\t\t\t<string>CA92.1</string>
\t\t\t</array>
\t\t</dict>
\t</array>
</dict>
</plist>
`;

async function patchIosPrivacyManifest(): Promise<void> {
  if (!(await exists(IOS_PLIST))) return; // patchIos() already said so

  await writeFile(IOS_PRIVACY_MANIFEST, IOS_PRIVACY_MANIFEST_XML);
  log(`${IOS_PRIVACY_MANIFEST} written.`);

  // Writing the file is not enough: it only ships if it is a member of the App target's
  // "Copy Bundle Resources" phase, and that lives in project.pbxproj — a format this script
  // will not edit blind, because a malformed pbxproj breaks the whole Xcode project rather
  // than one feature. So: check, and keep saying so on every sync until a human does it.
  const pbxproj = (await exists(IOS_PBXPROJ)) ? await readFile(IOS_PBXPROJ, 'utf8') : '';
  if (!pbxproj.includes('PrivacyInfo.xcprivacy')) {
    log('ACTION REQUIRED — add PrivacyInfo.xcprivacy to the App target in Xcode');
    log('  (drag ios/App/App/PrivacyInfo.xcprivacy into the App group, tick the App target).');
    log('  Without it the file is not in the bundle and App Store Connect rejects the upload');
    log('  with ITMS-91053: Missing API declaration.');
  }
}

/**
 * The half of the backup story this script CANNOT write, said out loud on every sync.
 *
 * `patchAndroidBackup` keeps the sealed vault off Google Drive with three mechanisms and a
 * paragraph explaining why a non-custodial wallet's storage must not leave the device. iOS
 * gets none of it: `@capacitor/preferences` is `UserDefaults`, which lands in
 * `Library/Preferences/<bundle>.plist`, which iCloud and iTunes back up by default and
 * restore onto a DIFFERENT device. What restores is `cosmos.w.<id>` — the AES-GCM sealed
 * seed and mnemonic, grindable offline against an 8-character minimum password — plus
 * `cosmos.wallets` in the clear: name, email, birthdate, gender, avatar.
 *
 * The device-unlock envelope is the one part that does NOT travel: its wrapping key is
 * written `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`, so the restored copy opens
 * nothing. The gap is the vault the envelope was built to sit beside.
 *
 * There is no Info.plist key for this — the fix is native, either moving iOS storage to a
 * Keychain item under `…ThisDeviceOnly` or setting `NSURLIsExcludedFromBackupKey` on the
 * preferences file at startup. Both need a device to verify, so this script reports rather
 * than guesses, in the same shape as the PrivacyInfo notice above.
 */
async function reportIosBackupGap(): Promise<void> {
  if (!(await exists(IOS_PLIST))) return; // patchIos() already said so
  log('ACTION REQUIRED — iOS storage is still backup-eligible.');
  log('  UserDefaults (Library/Preferences/<bundle>.plist) holds the sealed vault and the');
  log('  plaintext wallet list, and iCloud restores it onto another device. Android is');
  log('  covered by allowBackup=false + dataExtractionRules; iOS needs native work:');
  log('  move storage to a Keychain item with kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly,');
  log('  or set NSURLIsExcludedFromBackupKey on the preferences file at startup.');
}

await patchAndroid();
await patchAndroidBackup();
await patchIos();
await patchIosPrivacyManifest();
await reportIosBackupGap();
